[package]
name = "kube"
version = "0.50.1"
description = "Kubernetes client and futures controller runtime"
authors = [
  "clux <sszynrae@gmail.com>",
  "Teo Klestrup Röijezon <teo@nullable.se>",
  "kazk <kazk.dev@gmail.com>",
  "ynqa <un.pensiero.vano@gmail.com>",
]
license = "Apache-2.0"
repository = "https://github.com/clux/kube-rs"
readme = "../README.md"
keywords = ["kubernetes", "client", "runtime", "reflector", "informer"]
categories = ["web-programming::http-client"]
edition = "2018"

[features]
default = ["native-tls"]
native-tls = ["openssl", "hyper-tls", "tokio-native-tls"]
rustls-tls = ["hyper-rustls", "tokio-rustls"]
derive = ["kube-derive"]
jsonpatch = ["json-patch"]
ws = ["tokio-tungstenite"]
oauth = ["tame-oauth"]
gzip = ["async-compression"]

[package.metadata.docs.rs]
features = ["derive", "ws", "oauth", "jsonpatch"]
# Define the configuration attribute `docsrs`. Used to enable `doc_cfg` feature.
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
dirs = { package = "dirs-next", version = "2.0.0" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
serde_yaml = "0.8.14"
http = "0.2.2"
url = "2.2.0"
log = "0.4.11"
either = "1.6.1"
thiserror = "1.0.23"
futures = "0.3.8"
pem = "0.8.2"
openssl = { version = "0.10.32", optional = true }
tokio-native-tls = { version = "0.3.0", optional = true }
tokio-rustls = { version = "0.22.0", features = ["dangerous_configuration"], optional = true }
bytes = "1.0.0"
Inflector = "0.11.4"
tokio = { version = "1.0.1", features = ["time", "signal", "sync"] }
static_assertions = "1.1.0"
kube-derive = { path = "../kube-derive", version = "^0.50.0", optional = true }
jsonpath_lib = "0.2.6"
tokio-util = { version = "0.6.0", features = ["io", "codec"] }
json-patch = { version = "0.2.6", optional = true }
hyper = { version = "0.14.2", features = ["client", "http1", "stream", "tcp"] }
hyper-tls = { version = "0.5.0", default-features=false, features="vendored", optional = true }
hyper-rustls = { version = "0.22.1", optional = true }
tokio-tungstenite = { version = "0.13.0", optional = true }
tower = { version = "0.4.5", features = ["buffer", "util"] }
async-compression = { version = "0.3.7", features = ["gzip", "tokio"], optional = true }
hyper-timeout = "0.4.1"
tame-oauth = { version = "0.4.7", features = ["gcp"], optional = true }
pin-project = "1.0.4"

[dependencies.k8s-openapi]
version = "0.11.0"
default-features = false
features = []

[dev-dependencies]
tempfile = "3.1.0"
tokio = { version = "1.0.1", features = ["full"] }
schemars = "0.8.0"
tokio-test = "0.4.0"
tower-test = "0.4.0"

[dev-dependencies.k8s-openapi]
version = "0.11.0"
default-features = false
features = ["v1_19"]
